### ISSUE TITLE
Add "Auto Indent" Option to Right Click Menu

### ISSUE THREAD

**Issue by three3211** [vcfvct/brackets-file-format#2]
It would be nice to have the "Auto Indent" option added to the right click menu. Another plugin, Beautify, has this ability. This is just an enhancement, not a bug or issue.

**Comment by vcfvct** [comment]
Thanks for the feedback. 
I just added that auto indent option to the context menu as you suggested.

**Comment by three3211** [comment]
Wow, that was fast! Thank you very much for the update.
